plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.allcomp.allegro'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.allcomp.allegro'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }
}
